# SafeLink - Secure and Modern VPN App
name: safelink_vpn
description: SafeLink provides secure and encrypted internet access through OpenVPN protocol with modern UI design.
publish_to: 'none'

# App Version
version: 1.0.4+4

# Homepage and repository links (required for Play Store)
homepage: https://yourwebsite.com
repository: https://github.com/yourusername/free-vpn-app

environment:
  sdk: ^3.6.1

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.7.2

  # Cupertino style icons
  cupertino_icons: ^1.0.8

  # For API Call
  http: ^1.3.0

  # Converting CSV data to List
  csv: ^6.0.0

  # For Lottie Animation
  lottie: ^3.3.1

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads - REMOVED COMPLETELY (No ads for now)
  # google_mobile_ads: ^5.3.1

  # For firebase
  firebase_core: ^3.12.1

  # For Remote Config
  firebase_remote_config: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

  # Encourages good practices
  flutter_lints: ^5.0.0

  # For generating app icons
  flutter_launcher_icons: ^0.13.1

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#00796B"