// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUi42uUF98kFc1Wg6rnAqp1DOyDcvMxVU',
    appId: '1:365239488057:web:6428d663b338b58ad6c7e8',
    messagingSenderId: '365239488057',
    projectId: 'safe-link-vpn',
    authDomain: 'safe-link-vpn.firebaseapp.com',
    storageBucket: 'safe-link-vpn.firebasestorage.app',
    measurementId: 'G-LHCXB7V0TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgvgpyFCUVbKv37GibebvnPe6jIT9OPg',
    appId: '1:365239488057:android:fe89916f0f133f57d6c7e8',
    messagingSenderId: '365239488057',
    projectId: 'safe-link-vpn',
    storageBucket: 'safe-link-vpn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvIwYJe-biOU-Zp5RYXsQ07gAY3AQ47I',
    appId: '1:365239488057:ios:cd4a579bca5fe687d6c7e8',
    messagingSenderId: '365239488057',
    projectId: 'safe-link-vpn',
    storageBucket: 'safe-link-vpn.firebasestorage.app',
    iosBundleId: 'com.example.virtualPrivateNetwork',
  );
}
